In [2]:
import tensorflow as tf

In [4]:
# 创建变量
w = tf.Variable(initial_value=tf.random_normal(shape=(1,4), mean=100, stddev=0.3), name='W')
b = tf.Variable(tf.zeros([4]), name='b')

Instructions for updating:
Colocations handled automatically by placer.


In [5]:
[w, b]

[<tf.Variable 'W:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'b:0' shape=(4,) dtype=float32_ref>]

In [6]:
# 初始化变量
sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run([w, b])

[array([[ 99.938194,  99.591034, 100.31835 , 100.86395 ]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [7]:
sess.run(tf.assign_add(b, tf.ones(4)))

array([1., 1., 1., 1.], dtype=float32)

In [8]:
sess.run(b)

array([1., 1., 1., 1.], dtype=float32)

In [12]:
# 创建saver
saver = tf.train.Saver({'w': w, 'b': b})
saver.save(sess, './summary/test.ckpt', global_step=0)
sess.run(tf.assign_add(b, tf.ones(4)))

array([2., 2., 2., 2.], dtype=float32)

In [13]:
saver.restore(sess, './summary/test.ckpt-0')
sess.run(b)

INFO:tensorflow:Restoring parameters from ./summary/test.ckpt-0


array([1., 1., 1., 1.], dtype=float32)